[commands.tsc]
command = "tsc"
binPath = "./node_modules/.bin"
description = "Compile .ts files"

[commands.mocha]
command = "mocha -r ts-node/register ./test/**/*.spec.ts"
binPath = "./node_modules/.bin"
description = "Run tests"
visible = false